// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContactLog = `-- name: CreateContactLog :one
INSERT INTO contacts (relationship_id, user_id, channel, note, contacted_at)
VALUES ($1, $2, $3, $4, COALESCE($5, NOW()))
RETURNING id, relationship_id, user_id, channel, note, contacted_at, created_at
`

type CreateContactLogParams struct {
	RelationshipID int64       `json:"relationship_id"`
	UserID         int64       `json:"user_id"`
	Channel        string      `json:"channel"`
	Note           pgtype.Text `json:"note"`
	Column5        interface{} `json:"column_5"`
}

func (q *Queries) CreateContactLog(ctx context.Context, arg CreateContactLogParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContactLog,
		arg.RelationshipID,
		arg.UserID,
		arg.Channel,
		arg.Note,
		arg.Column5,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.RelationshipID,
		&i.UserID,
		&i.Channel,
		&i.Note,
		&i.ContactedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = $1 AND user_id = $2
`

type DeleteContactParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.ID, arg.UserID)
	return err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, relationship_id, user_id, channel, note, contacted_at, created_at
FROM contacts
WHERE id = $1
  AND user_id = $2
`

type GetContactByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.RelationshipID,
		&i.UserID,
		&i.Channel,
		&i.Note,
		&i.ContactedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getContactsByRelationship = `-- name: GetContactsByRelationship :many
SELECT id, relationship_id, user_id, channel, note, contacted_at, created_at
FROM contacts
WHERE relationship_id = $1
ORDER BY contacted_at DESC
`

func (q *Queries) GetContactsByRelationship(ctx context.Context, relationshipID int64) ([]Contact, error) {
	rows, err := q.db.Query(ctx, getContactsByRelationship, relationshipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.RelationshipID,
			&i.UserID,
			&i.Channel,
			&i.Note,
			&i.ContactedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingDriftReminders = `-- name: GetPendingDriftReminders :many
SELECT 
    id, owner_id, name, type,
    drift_threshold_days,
    last_contact_at,
    next_contact_at
FROM relationships
WHERE next_contact_at IS NOT NULL
  AND next_contact_at <= NOW()
`

type GetPendingDriftRemindersRow struct {
	ID                 int64              `json:"id"`
	OwnerID            int64              `json:"owner_id"`
	Name               string             `json:"name"`
	Type               pgtype.Text        `json:"type"`
	DriftThresholdDays int32              `json:"drift_threshold_days"`
	LastContactAt      pgtype.Timestamptz `json:"last_contact_at"`
	NextContactAt      pgtype.Timestamptz `json:"next_contact_at"`
}

func (q *Queries) GetPendingDriftReminders(ctx context.Context) ([]GetPendingDriftRemindersRow, error) {
	rows, err := q.db.Query(ctx, getPendingDriftReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingDriftRemindersRow
	for rows.Next() {
		var i GetPendingDriftRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.DriftThresholdDays,
			&i.LastContactAt,
			&i.NextContactAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsForDrift = `-- name: ListRelationshipsForDrift :many
SELECT 
    id, owner_id, name, type,
    drift_threshold_days,
    last_contact_at,
    next_contact_at
FROM relationships
WHERE owner_id = $1
`

type ListRelationshipsForDriftRow struct {
	ID                 int64              `json:"id"`
	OwnerID            int64              `json:"owner_id"`
	Name               string             `json:"name"`
	Type               pgtype.Text        `json:"type"`
	DriftThresholdDays int32              `json:"drift_threshold_days"`
	LastContactAt      pgtype.Timestamptz `json:"last_contact_at"`
	NextContactAt      pgtype.Timestamptz `json:"next_contact_at"`
}

func (q *Queries) ListRelationshipsForDrift(ctx context.Context, ownerID int64) ([]ListRelationshipsForDriftRow, error) {
	rows, err := q.db.Query(ctx, listRelationshipsForDrift, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationshipsForDriftRow
	for rows.Next() {
		var i ListRelationshipsForDriftRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.DriftThresholdDays,
			&i.LastContactAt,
			&i.NextContactAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderAsSent = `-- name: MarkReminderAsSent :exec
UPDATE relationships
SET 
    last_reminder_sent_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkReminderAsSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markReminderAsSent, id)
	return err
}

const searchRelationships = `-- name: SearchRelationships :many
SELECT id, owner_id, name, type, how_we_met, birthday, location, avatar_url, tags, drift_threshold_days, drift_status, warmth_score, last_reminder_sent_at, next_contact_at, last_contact_at, created_at, updated_at
FROM relationships
WHERE owner_id = $1
  AND (
    to_tsvector(
      'english',
      coalesce(name, '') || ' ' ||
      coalesce(type, '') || ' ' ||
      coalesce(how_we_met, '')
    )
    @@ plainto_tsquery('english', $2)
  )
ORDER BY last_contact_at DESC
`

type SearchRelationshipsParams struct {
	OwnerID        int64  `json:"owner_id"`
	PlaintoTsquery string `json:"plainto_tsquery"`
}

func (q *Queries) SearchRelationships(ctx context.Context, arg SearchRelationshipsParams) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, searchRelationships, arg.OwnerID, arg.PlaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relationship
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.HowWeMet,
			&i.Birthday,
			&i.Location,
			&i.AvatarUrl,
			&i.Tags,
			&i.DriftThresholdDays,
			&i.DriftStatus,
			&i.WarmthScore,
			&i.LastReminderSentAt,
			&i.NextContactAt,
			&i.LastContactAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET
    channel = COALESCE($3, channel),
    note = COALESCE($4, note),
    contacted_at = COALESCE($5, contacted_at),
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
RETURNING id, relationship_id, user_id, channel, note, contacted_at, created_at
`

type UpdateContactParams struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Channel     string             `json:"channel"`
	Note        pgtype.Text        `json:"note"`
	ContactedAt pgtype.Timestamptz `json:"contacted_at"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ID,
		arg.UserID,
		arg.Channel,
		arg.Note,
		arg.ContactedAt,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.RelationshipID,
		&i.UserID,
		&i.Channel,
		&i.Note,
		&i.ContactedAt,
		&i.CreatedAt,
	)
	return i, err
}
