// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContactLog = `-- name: CreateContactLog :one
INSERT INTO contacts (relationship_id, user_id, channel, note, contacted_at)
VALUES ($1, $2, $3, $4, COALESCE($5, NOW()))
RETURNING id, relationship_id, user_id, channel, note, contacted_at, created_at
`

type CreateContactLogParams struct {
	RelationshipID int64       `json:"relationship_id"`
	UserID         int64       `json:"user_id"`
	Channel        string      `json:"channel"`
	Note           pgtype.Text `json:"note"`
	Column5        interface{} `json:"column_5"`
}

func (q *Queries) CreateContactLog(ctx context.Context, arg CreateContactLogParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContactLog,
		arg.RelationshipID,
		arg.UserID,
		arg.Channel,
		arg.Note,
		arg.Column5,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.RelationshipID,
		&i.UserID,
		&i.Channel,
		&i.Note,
		&i.ContactedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingDriftReminders = `-- name: GetPendingDriftReminders :many
SELECT id, owner_id, name, type, drift_interval_days, last_contact_at
FROM relationships
WHERE last_contact_at IS NOT NULL 
  AND reminder_sent = FALSE
`

type GetPendingDriftRemindersRow struct {
	ID                int64              `json:"id"`
	OwnerID           int64              `json:"owner_id"`
	Name              string             `json:"name"`
	Type              pgtype.Text        `json:"type"`
	DriftIntervalDays pgtype.Text        `json:"drift_interval_days"`
	LastContactAt     pgtype.Timestamptz `json:"last_contact_at"`
}

func (q *Queries) GetPendingDriftReminders(ctx context.Context) ([]GetPendingDriftRemindersRow, error) {
	rows, err := q.db.Query(ctx, getPendingDriftReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingDriftRemindersRow
	for rows.Next() {
		var i GetPendingDriftRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.DriftIntervalDays,
			&i.LastContactAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsForDrift = `-- name: ListRelationshipsForDrift :many
SELECT id, owner_id, name, type, drift_interval_days, last_contact_at 
FROM relationships
WHERE owner_id = $1
`

type ListRelationshipsForDriftRow struct {
	ID                int64              `json:"id"`
	OwnerID           int64              `json:"owner_id"`
	Name              string             `json:"name"`
	Type              pgtype.Text        `json:"type"`
	DriftIntervalDays pgtype.Text        `json:"drift_interval_days"`
	LastContactAt     pgtype.Timestamptz `json:"last_contact_at"`
}

func (q *Queries) ListRelationshipsForDrift(ctx context.Context, ownerID int64) ([]ListRelationshipsForDriftRow, error) {
	rows, err := q.db.Query(ctx, listRelationshipsForDrift, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationshipsForDriftRow
	for rows.Next() {
		var i ListRelationshipsForDriftRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.DriftIntervalDays,
			&i.LastContactAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderAsSent = `-- name: MarkReminderAsSent :exec
UPDATE relationships
SET reminder_sent = TRUE
WHERE id = $1
`

func (q *Queries) MarkReminderAsSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markReminderAsSent, id)
	return err
}

const searchRelationships = `-- name: SearchRelationships :many
SELECT id, owner_id, name, type, how_we_met, birthday, location, avatar_url, tags, drift_interval_days, reminder_sent, last_contact_at, created_at, updated_at FROM relationships
WHERE owner_id = $1
  AND (
    to_tsvector('english', coalesce(name, '') || ' ' || coalesce(type, '') || ' ' || coalesce(how_we_met, '')) 
    @@ plainto_tsquery('english', $2)
  )
ORDER BY last_contact_at DESC
`

type SearchRelationshipsParams struct {
	OwnerID        int64  `json:"owner_id"`
	PlaintoTsquery string `json:"plainto_tsquery"`
}

func (q *Queries) SearchRelationships(ctx context.Context, arg SearchRelationshipsParams) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, searchRelationships, arg.OwnerID, arg.PlaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relationship
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.HowWeMet,
			&i.Birthday,
			&i.Location,
			&i.AvatarUrl,
			&i.Tags,
			&i.DriftIntervalDays,
			&i.ReminderSent,
			&i.LastContactAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelationshipLastContact = `-- name: UpdateRelationshipLastContact :exec
UPDATE relationships
SET 
    last_contact_at = $1,
    reminder_sent = FALSE, -- Reset the worker alert state automatically on new contact
    updated_at = NOW()
WHERE id = $2 AND owner_id = $3
`

type UpdateRelationshipLastContactParams struct {
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	ID            int64              `json:"id"`
	OwnerID       int64              `json:"owner_id"`
}

func (q *Queries) UpdateRelationshipLastContact(ctx context.Context, arg UpdateRelationshipLastContactParams) error {
	_, err := q.db.Exec(ctx, updateRelationshipLastContact, arg.LastContactAt, arg.ID, arg.OwnerID)
	return err
}
