// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (
    user_id,
    email,
    otp_hash,
    expires_at
)
VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, email, otp_hash, attempts, is_used, expires_at, created_at
`

type CreateEmailVerificationParams struct {
	UserID    int64            `json:"user_id"`
	Email     string           `json:"email"`
	OtpHash   string           `json:"otp_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification,
		arg.UserID,
		arg.Email,
		arg.OtpHash,
		arg.ExpiresAt,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.OtpHash,
		&i.Attempts,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestEmailVerification = `-- name: GetLatestEmailVerification :one
SELECT id, user_id, email, otp_hash, attempts, is_used, expires_at, created_at
FROM email_verifications
WHERE email = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestEmailVerification(ctx context.Context, email string) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getLatestEmailVerification, email)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.OtpHash,
		&i.Attempts,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications
SET is_used = TRUE
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEmailVerificationUsed, id)
	return err
}
