// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        int64            `json:"id"`
	UserID    int64            `json:"user_id"`
	SessionID int64            `json:"session_id"`
	TokenHash string           `json:"token_hash"`
	IsRevoked pgtype.Bool      `json:"is_revoked"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID         int64            `json:"id"`
	UserID     int64            `json:"user_id"`
	TokenHash  string           `json:"token_hash"`
	DeviceName pgtype.Text      `json:"device_name"`
	DeviceType pgtype.Text      `json:"device_type"`
	IpAddress  *netip.Addr      `json:"ip_address"`
	UserAgent  pgtype.Text      `json:"user_agent"`
	IsActive   pgtype.Bool      `json:"is_active"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                   int64            `json:"id"`
	Username             string           `json:"username"`
	Email                string           `json:"email"`
	DisplayName          pgtype.Text      `json:"display_name"`
	AvatarUrl            pgtype.Text      `json:"avatar_url"`
	Bio                  pgtype.Text      `json:"bio"`
	Timezone             pgtype.Text      `json:"timezone"`
	IsVerified           pgtype.Bool      `json:"is_verified"`
	IsActive             pgtype.Bool      `json:"is_active"`
	PrivacySetting       pgtype.Text      `json:"privacy_setting"`
	NotificationsEnabled pgtype.Bool      `json:"notifications_enabled"`
	PushToken            pgtype.Text      `json:"push_token"`
	LastSeenAt           pgtype.Timestamp `json:"last_seen_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type UserAuth struct {
	ID                int64            `json:"id"`
	UserID            int64            `json:"user_id"`
	PasswordHash      string           `json:"password_hash"`
	MfaEnabled        pgtype.Bool      `json:"mfa_enabled"`
	MfaSecret         pgtype.Text      `json:"mfa_secret"`
	FailedAttempts    pgtype.Int4      `json:"failed_attempts"`
	LockedUntil       pgtype.Timestamp `json:"locked_until"`
	PasswordChangedAt pgtype.Timestamp `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}
