// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: private_notes.sql

package db

import (
	"context"
)

const deletePrivateNote = `-- name: DeletePrivateNote :exec
DELETE FROM private_notes
WHERE relationship_id = $1 AND user_id = $2
`

type DeletePrivateNoteParams struct {
	RelationshipID int64 `json:"relationship_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) DeletePrivateNote(ctx context.Context, arg DeletePrivateNoteParams) error {
	_, err := q.db.Exec(ctx, deletePrivateNote, arg.RelationshipID, arg.UserID)
	return err
}

const getPrivateNote = `-- name: GetPrivateNote :one
SELECT id, user_id, relationship_id, content, created_at, updated_at
FROM private_notes
WHERE relationship_id = $1 AND user_id = $2
`

type GetPrivateNoteParams struct {
	RelationshipID int64 `json:"relationship_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) GetPrivateNote(ctx context.Context, arg GetPrivateNoteParams) (PrivateNote, error) {
	row := q.db.QueryRow(ctx, getPrivateNote, arg.RelationshipID, arg.UserID)
	var i PrivateNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RelationshipID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPrivateNote = `-- name: UpsertPrivateNote :one
INSERT INTO private_notes (user_id, relationship_id, content, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, relationship_id) 
DO UPDATE SET 
    content = EXCLUDED.content,
    updated_at = NOW()
RETURNING id, user_id, relationship_id, content, created_at, updated_at
`

type UpsertPrivateNoteParams struct {
	UserID         int64  `json:"user_id"`
	RelationshipID int64  `json:"relationship_id"`
	Content        string `json:"content"`
}

func (q *Queries) UpsertPrivateNote(ctx context.Context, arg UpsertPrivateNoteParams) (PrivateNote, error) {
	row := q.db.QueryRow(ctx, upsertPrivateNote, arg.UserID, arg.RelationshipID, arg.Content)
	var i PrivateNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RelationshipID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
