// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, 
    session_id, 
    token_hash, 
    expires_at
) VALUES (
    $1, $2, $3, $4
) 
RETURNING id, user_id, session_id, token_hash, is_revoked, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64            `json:"user_id"`
	SessionID int64            `json:"session_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.SessionID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.TokenHash,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at <= NOW()
`

// Run this on a cron job or background worker to keep your DB lean
func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getActiveTokenByHash = `-- name: GetActiveTokenByHash :one
SELECT id, user_id, session_id, token_hash, is_revoked, expires_at, created_at
FROM refresh_tokens
WHERE token_hash = $1 
  AND is_revoked = FALSE 
  AND expires_at > NOW()
LIMIT 1
`

// Retrieves a token only if it hasn't been explicitly revoked and hasn't expired yet
func (q *Queries) GetActiveTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getActiveTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.TokenHash,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE refresh_tokens    
SET is_revoked = TRUE
WHERE user_id = $1 
  AND is_revoked = FALSE
`

// Useful for "log out of all devices" or global password resets
func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	return err
}

const revokeSpecificSession = `-- name: RevokeSpecificSession :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE session_id = $1 
  AND is_revoked = FALSE
`

// Useful for logging out of one specific device/browser session
func (q *Queries) RevokeSpecificSession(ctx context.Context, sessionID int64) error {
	_, err := q.db.Exec(ctx, revokeSpecificSession, sessionID)
	return err
}

const revokeTokenByHash = `-- name: RevokeTokenByHash :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE token_hash = $1
`

func (q *Queries) RevokeTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeTokenByHash, tokenHash)
	return err
}
