// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relationships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendTags = `-- name: AppendTags :one
UPDATE relationships
SET 
    tags = ARRAY(
        SELECT DISTINCT unnest(array_cat(tags, $1::text[]))
    ),
    updated_at = NOW()
WHERE id = $2 AND owner_id = $3
RETURNING id, owner_id, name, tags, updated_at
`

type AppendTagsParams struct {
	Column1 []string `json:"column_1"`
	ID      int64    `json:"id"`
	OwnerID int64    `json:"owner_id"`
}

type AppendTagsRow struct {
	ID        int64              `json:"id"`
	OwnerID   int64              `json:"owner_id"`
	Name      string             `json:"name"`
	Tags      []string           `json:"tags"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AppendTags(ctx context.Context, arg AppendTagsParams) (AppendTagsRow, error) {
	row := q.db.QueryRow(ctx, appendTags, arg.Column1, arg.ID, arg.OwnerID)
	var i AppendTagsRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Tags,
		&i.UpdatedAt,
	)
	return i, err
}

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationships (
    owner_id, 
    name, 
    type, 
    how_we_met, 
    birthday, 
    location, 
    tags,
    drift_threshold_days,
    next_contact_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING 
    id, owner_id, name, type, how_we_met, birthday, location, avatar_url, tags,
    drift_threshold_days,
    drift_status,
    warmth_score,
    last_reminder_sent_at,
    next_contact_at,
    last_contact_at,
    created_at, updated_at
`

type CreateRelationshipParams struct {
	OwnerID            int64              `json:"owner_id"`
	Name               string             `json:"name"`
	Type               pgtype.Text        `json:"type"`
	HowWeMet           pgtype.Text        `json:"how_we_met"`
	Birthday           pgtype.Date        `json:"birthday"`
	Location           pgtype.Text        `json:"location"`
	Tags               []string           `json:"tags"`
	DriftThresholdDays int32              `json:"drift_threshold_days"`
	NextContactAt      pgtype.Timestamptz `json:"next_contact_at"`
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, createRelationship,
		arg.OwnerID,
		arg.Name,
		arg.Type,
		arg.HowWeMet,
		arg.Birthday,
		arg.Location,
		arg.Tags,
		arg.DriftThresholdDays,
		arg.NextContactAt,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Type,
		&i.HowWeMet,
		&i.Birthday,
		&i.Location,
		&i.AvatarUrl,
		&i.Tags,
		&i.DriftThresholdDays,
		&i.DriftStatus,
		&i.WarmthScore,
		&i.LastReminderSentAt,
		&i.NextContactAt,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM relationships
WHERE id = $1 AND owner_id = $2
`

type DeleteRelationshipParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) DeleteRelationship(ctx context.Context, arg DeleteRelationshipParams) error {
	_, err := q.db.Exec(ctx, deleteRelationship, arg.ID, arg.OwnerID)
	return err
}

const getRelationshipByID = `-- name: GetRelationshipByID :one
SELECT 
    id, owner_id, name, type, how_we_met, birthday, location, avatar_url, tags,
    drift_threshold_days,
    drift_status,
    warmth_score,
    last_reminder_sent_at,
    next_contact_at,
    last_contact_at,
    created_at, updated_at
FROM relationships
WHERE id = $1 AND owner_id = $2
`

type GetRelationshipByIDParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) GetRelationshipByID(ctx context.Context, arg GetRelationshipByIDParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, getRelationshipByID, arg.ID, arg.OwnerID)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Type,
		&i.HowWeMet,
		&i.Birthday,
		&i.Location,
		&i.AvatarUrl,
		&i.Tags,
		&i.DriftThresholdDays,
		&i.DriftStatus,
		&i.WarmthScore,
		&i.LastReminderSentAt,
		&i.NextContactAt,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRelationships = `-- name: ListRelationships :many
SELECT 
    id, owner_id, name, type, how_we_met, location, birthday, tags,
    drift_threshold_days,
    drift_status,
    warmth_score,
    last_contact_at,
    next_contact_at,
    created_at
FROM relationships
WHERE owner_id = $1 
  AND ($2::text = '' OR type = $2)
ORDER BY next_contact_at ASC NULLS LAST
`

type ListRelationshipsParams struct {
	OwnerID int64  `json:"owner_id"`
	Column2 string `json:"column_2"`
}

type ListRelationshipsRow struct {
	ID                 int64              `json:"id"`
	OwnerID            int64              `json:"owner_id"`
	Name               string             `json:"name"`
	Type               pgtype.Text        `json:"type"`
	HowWeMet           pgtype.Text        `json:"how_we_met"`
	Location           pgtype.Text        `json:"location"`
	Birthday           pgtype.Date        `json:"birthday"`
	Tags               []string           `json:"tags"`
	DriftThresholdDays int32              `json:"drift_threshold_days"`
	DriftStatus        string             `json:"drift_status"`
	WarmthScore        pgtype.Int4        `json:"warmth_score"`
	LastContactAt      pgtype.Timestamptz `json:"last_contact_at"`
	NextContactAt      pgtype.Timestamptz `json:"next_contact_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRelationships(ctx context.Context, arg ListRelationshipsParams) ([]ListRelationshipsRow, error) {
	rows, err := q.db.Query(ctx, listRelationships, arg.OwnerID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelationshipsRow
	for rows.Next() {
		var i ListRelationshipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Type,
			&i.HowWeMet,
			&i.Location,
			&i.Birthday,
			&i.Tags,
			&i.DriftThresholdDays,
			&i.DriftStatus,
			&i.WarmthScore,
			&i.LastContactAt,
			&i.NextContactAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSingleTag = `-- name: RemoveSingleTag :one
UPDATE relationships
SET 
    tags = array_remove(tags, $1::text),
    updated_at = NOW()
WHERE id = $2 AND owner_id = $3
RETURNING id, owner_id, name, tags, updated_at
`

type RemoveSingleTagParams struct {
	Column1 string `json:"column_1"`
	ID      int64  `json:"id"`
	OwnerID int64  `json:"owner_id"`
}

type RemoveSingleTagRow struct {
	ID        int64              `json:"id"`
	OwnerID   int64              `json:"owner_id"`
	Name      string             `json:"name"`
	Tags      []string           `json:"tags"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RemoveSingleTag(ctx context.Context, arg RemoveSingleTagParams) (RemoveSingleTagRow, error) {
	row := q.db.QueryRow(ctx, removeSingleTag, arg.Column1, arg.ID, arg.OwnerID)
	var i RemoveSingleTagRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Tags,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceTags = `-- name: ReplaceTags :one
UPDATE relationships
SET 
    tags = $1,
    updated_at = NOW()
WHERE id = $2 AND owner_id = $3
RETURNING id, owner_id, name, tags, updated_at
`

type ReplaceTagsParams struct {
	Tags    []string `json:"tags"`
	ID      int64    `json:"id"`
	OwnerID int64    `json:"owner_id"`
}

type ReplaceTagsRow struct {
	ID        int64              `json:"id"`
	OwnerID   int64              `json:"owner_id"`
	Name      string             `json:"name"`
	Tags      []string           `json:"tags"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReplaceTags(ctx context.Context, arg ReplaceTagsParams) (ReplaceTagsRow, error) {
	row := q.db.QueryRow(ctx, replaceTags, arg.Tags, arg.ID, arg.OwnerID)
	var i ReplaceTagsRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Tags,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRelationship = `-- name: UpdateRelationship :one
UPDATE relationships
SET 
    name = COALESCE($3, name),
    type = COALESCE($4, type),
    how_we_met = COALESCE($5, how_we_met),
    birthday = COALESCE($6, birthday),
    location = COALESCE($7, location),
    avatar_url = COALESCE($8, avatar_url),

    drift_threshold_days = COALESCE($9, drift_threshold_days),

    updated_at = NOW()
WHERE id = $1 AND owner_id = $2
RETURNING 
    id, owner_id, name, type, how_we_met, birthday, location, avatar_url, tags,
    drift_threshold_days,
    drift_status,
    warmth_score,
    last_reminder_sent_at,
    next_contact_at,
    last_contact_at,
    created_at, updated_at
`

type UpdateRelationshipParams struct {
	ID                 int64       `json:"id"`
	OwnerID            int64       `json:"owner_id"`
	Name               pgtype.Text `json:"name"`
	Type               pgtype.Text `json:"type"`
	HowWeMet           pgtype.Text `json:"how_we_met"`
	Birthday           pgtype.Date `json:"birthday"`
	Location           pgtype.Text `json:"location"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	DriftThresholdDays pgtype.Int4 `json:"drift_threshold_days"`
}

func (q *Queries) UpdateRelationship(ctx context.Context, arg UpdateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, updateRelationship,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Type,
		arg.HowWeMet,
		arg.Birthday,
		arg.Location,
		arg.AvatarUrl,
		arg.DriftThresholdDays,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Type,
		&i.HowWeMet,
		&i.Birthday,
		&i.Location,
		&i.AvatarUrl,
		&i.Tags,
		&i.DriftThresholdDays,
		&i.DriftStatus,
		&i.WarmthScore,
		&i.LastReminderSentAt,
		&i.NextContactAt,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
