// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relationships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationships (
    owner_id, 
    name, 
    type, 
    how_we_met, 
    birthday, 
    location, 
    tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, owner_id, name, type, how_we_met, birthday, location, tags, last_contact_at, created_at, updated_at, deleted_at
`

type CreateRelationshipParams struct {
	OwnerID  int64       `json:"owner_id"`
	Name     string      `json:"name"`
	Type     pgtype.Text `json:"type"`
	HowWeMet pgtype.Text `json:"how_we_met"`
	Birthday pgtype.Date `json:"birthday"`
	Location pgtype.Text `json:"location"`
	Tags     []string    `json:"tags"`
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, createRelationship,
		arg.OwnerID,
		arg.Name,
		arg.Type,
		arg.HowWeMet,
		arg.Birthday,
		arg.Location,
		arg.Tags,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Type,
		&i.HowWeMet,
		&i.Birthday,
		&i.Location,
		&i.Tags,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
