// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, 
    token_hash, 
    device_name, 
    device_type, 
    ip_address, 
    user_agent, 
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) 
RETURNING id, user_id, token_hash, device_name, device_type, ip_address, user_agent, is_active, expires_at, created_at
`

type CreateSessionParams struct {
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceName pgtype.Text        `json:"device_name"`
	DeviceType pgtype.Text        `json:"device_type"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceName,
		arg.DeviceType,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceName,
		&i.DeviceType,
		&i.IpAddress,
		&i.UserAgent,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAllUserSessions = `-- name: DeactivateAllUserSessions :exec
UPDATE sessions
SET is_active = FALSE
WHERE user_id = $1 
  AND id <> $2
  AND is_active = TRUE
`

type DeactivateAllUserSessionsParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

// Great for a "Log out of all other devices" feature
func (q *Queries) DeactivateAllUserSessions(ctx context.Context, arg DeactivateAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deactivateAllUserSessions, arg.UserID, arg.ID)
	return err
}

const deactivateSession = `-- name: DeactivateSession :exec
UPDATE sessions
SET is_active = FALSE
WHERE id = $1
`

// Standard single device logout
func (q *Queries) DeactivateSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateSession, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= NOW() 
   OR is_active = FALSE
`

// Housekeeping query to clean up dead rows over time
func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getActiveSessionByHash = `-- name: GetActiveSessionByHash :one
SELECT id, user_id, token_hash, device_name, device_type, ip_address, user_agent, is_active, expires_at, created_at
FROM sessions
WHERE token_hash = $1 
  AND is_active = TRUE 
  AND expires_at > NOW()
LIMIT 1
`

// Fetches the session details only if it's active and hasn't expired
func (q *Queries) GetActiveSessionByHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceName,
		&i.DeviceType,
		&i.IpAddress,
		&i.UserAgent,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionsByUser = `-- name: GetActiveSessionsByUser :many
SELECT id, device_name, device_type, ip_address, user_agent, expires_at, created_at
FROM sessions
WHERE user_id = $1 
  AND is_active = TRUE 
  AND expires_at > NOW()
ORDER BY created_at DESC
`

type GetActiveSessionsByUserRow struct {
	ID         int64              `json:"id"`
	DeviceName pgtype.Text        `json:"device_name"`
	DeviceType pgtype.Text        `json:"device_type"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Useful for showing a user a list of their "Logged-in Devices"
func (q *Queries) GetActiveSessionsByUser(ctx context.Context, userID int64) ([]GetActiveSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, getActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSessionsByUserRow
	for rows.Next() {
		var i GetActiveSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceName,
			&i.DeviceType,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions
SET expires_at = $2,
    ip_address = $3,
    user_agent = $4
WHERE id = $1 
  AND is_active = TRUE
`

type UpdateSessionActivityParams struct {
	ID        int64              `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

// Call this if you use a rolling session mechanism to extend expiration on use
func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.Exec(ctx, updateSessionActivity,
		arg.ID,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
