// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_auth.sql

package db

import (
	"context"
)

const createUserAuth = `-- name: CreateUserAuth :one
INSERT INTO user_auth (
    user_id,
    password_hash,
    mfa_enabled,
    failed_attempts
)
VALUES (
    $1, $2, FALSE, 0
)
RETURNING id, user_id, password_hash, mfa_enabled, mfa_secret, failed_attempts, locked_until, password_changed_at, created_at, updated_at
`

type CreateUserAuthParams struct {
	UserID       int64  `json:"user_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (UserAuth, error) {
	row := q.db.QueryRow(ctx, createUserAuth, arg.UserID, arg.PasswordHash)
	var i UserAuth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAuthByUserID = `-- name: GetUserAuthByUserID :one
SELECT id, user_id, password_hash, mfa_enabled, mfa_secret, failed_attempts, locked_until, password_changed_at, created_at, updated_at
FROM user_auth
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserAuthByUserID(ctx context.Context, userID int64) (UserAuth, error) {
	row := q.db.QueryRow(ctx, getUserAuthByUserID, userID)
	var i UserAuth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.MfaSecret,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE user_auth
SET password_hash = $2,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserPasswordParams struct {
	UserID       int64  `json:"user_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.UserID, arg.PasswordHash)
	return err
}
