// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    display_name,
    is_verified,
    is_active
)
VALUES (
    $1, $2, $3, FALSE, TRUE
)
RETURNING id, username, email, display_name, avatar_url, bio, timezone, is_verified, is_active, privacy_setting, notifications_enabled, push_token, last_seen_at, created_at, updated_at
`

type CreateUserParams struct {
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.IsVerified,
		&i.IsActive,
		&i.PrivacySetting,
		&i.NotificationsEnabled,
		&i.PushToken,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, avatar_url, bio, timezone, is_verified, is_active, privacy_setting, notifications_enabled, push_token, last_seen_at, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.IsVerified,
		&i.IsActive,
		&i.PrivacySetting,
		&i.NotificationsEnabled,
		&i.PushToken,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, avatar_url, bio, timezone, is_verified, is_active, privacy_setting, notifications_enabled, push_token, last_seen_at, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.IsVerified,
		&i.IsActive,
		&i.PrivacySetting,
		&i.NotificationsEnabled,
		&i.PushToken,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
